### ISSUE TITLE
Why does the WebGL drawing lag (ever so slightly) behind the CSS rendering?

### ISSUE THREAD

**Issue by trusktr** [keithclark/3d-model-element#18]
If you play close attention (more visible in Safari), then you'll notice that WebGL content lags slightly behind CSS content. For example, in this (example)[https://keithclark.co.uk/labs/3d-model-custom-element/examples/3d-scene/], move back a little, then jiggle the mouse around and the model seems to catch up to the motion of the floor a very short (but noticeable) moment later.

Curious to know why this happens.

**Comment by keithclark** [comment]
Think I've finally go to the bottom of this. It looks like a problem with that demo. Switching this...

https://github.com/keithclark/3d-model-element/blob/556d9b677a59ba09994cb22319d6a0f647cdb2ea/examples/3d-scene/demo.js#L25

...to the following fixes the issue for me:

```js
requestIdleCallback(update)
```
