### ISSUE TITLE
gLTF

### ISSUE THREAD

**Issue by Martin-Pitt** [keithclark/3d-model-element#4]
> Only supports then .obj model file format - other loaders will be added in the future.

I think the next best loader would be with the new gLTF specification that has incredible adoption in the industry at the moment as a standard file format of 3D content.

three.js already has a loader for this: https://threejs.org/docs/#examples/loaders/GLTFLoader

Could probably check if extension specifies a gLTF format (`.gltf`, `.glb`) and check if the Loader is present for it?

**Comment by keithclark** [comment]
The plan is to either allow loaders to be registered at runtime or imported during a build step (I'm leaning towards the latter at the moment). Either way, I still need to work out what the API for that would look like.

**Comment by keithclark** [comment]
I've added support for this here: #6, which I plan to merge soon. You should now be able to load gLTF models (with the `.gltf` extension) using:

```html
<body>
  <x-model src="/path/to/model.gltf"></x-model>

  <script src="/path/to/three.min.js"></script>
  <script src="/path/to/three-gltf-loader.min.js"></script>
  <script src="/path/to/model-element.js"></script>
</body>
```

_Note: At the moment you'll need to include the gLTF loader yourself as it's not bundled it with `model-element` and the versions in the Three repo aren't ES6 "module ready". As more of [Three's code is moved over to ES6 module format](https://github.com/mrdoob/three.js/issues/9562) I'll reassess and look to add it as a build dependency at a later date._

**Comment by keithclark** [comment]
I completely overlooked `.glb`. I'll add support for that when I get a chance. It _should_ just be a case of registering the alternative file extension to the existing loader.

**Comment by keithclark** [comment]
This is now merged and useable. Thanks for taking time to contribute 😁
